# Generated by Django 5.0.6 on 2026-04-22 08:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        ('incidents', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_id', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('WARNING', 'Warning'), ('INFO', 'Info')], db_index=True, default='WARNING', max_length=20)),
                ('status', models.CharField(choices=[('FIRING', 'Firing'), ('RESOLVED', 'Resolved'), ('ACKNOWLEDGED', 'Acknowledged'), ('SILENCED', 'Silenced')], db_index=True, default='FIRING', max_length=20)),
                ('source', models.CharField(choices=[('PROMETHEUS', 'Prometheus'), ('GRAFANA', 'Grafana'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('metric', models.CharField(blank=True, max_length=255, null=True)),
                ('current_value', models.CharField(blank=True, max_length=255, null=True)),
                ('threshold', models.CharField(blank=True, max_length=255, null=True)),
                ('labels', models.JSONField(blank=True, null=True)),
                ('annotations', models.JSONField(blank=True, null=True)),
                ('fired_at', models.DateTimeField(db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('silence_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('config_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='assets.configurationitem')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_alerts', to='incidents.incident')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='organizations.organization')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-fired_at'],
                'indexes': [models.Index(fields=['status', 'severity'], name='alerts_status_5203b6_idx'), models.Index(fields=['fired_at'], name='alerts_fired_a_21476b_idx')],
            },
        ),
    ]
