# Generated by Django 5.0.6 on 2026-05-02 13:52

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_rename_incidents_org_state_created_idx_incidents_organiz_b7b8b7_idx_and_more'),
        ('sla', '0002_businesscalendar_slaholiday'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE sla_definitions SET start_condition='{}', pause_condition='{}', stop_condition='{}', reset_condition='{}';"
        ),
        migrations.AlterField(
            model_name='sladefinition',
            name='pause_condition',
            field=models.JSONField(blank=True, default=dict, help_text='JSON conditions to pause the SLA.'),
        ),
        migrations.AlterField(
            model_name='sladefinition',
            name='reset_condition',
            field=models.JSONField(blank=True, default=dict, help_text='JSON conditions to reset the SLA.'),
        ),
        migrations.AlterField(
            model_name='sladefinition',
            name='start_condition',
            field=models.JSONField(default=dict, help_text='JSON conditions to start the SLA.'),
        ),
        migrations.AlterField(
            model_name='sladefinition',
            name='stop_condition',
            field=models.JSONField(default=dict, help_text='JSON conditions to stop the SLA.'),
        ),
        migrations.CreateModel(
            name='TaskSLA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=20)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('pause_time', models.DateTimeField(blank=True, null=True)),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('total_pause_duration', models.DurationField(default=datetime.timedelta)),
                ('business_elapsed_time', models.DurationField(default=datetime.timedelta)),
                ('percentage_elapsed', models.FloatField(default=0.0)),
                ('has_breached', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_slas', to='incidents.incident')),
                ('sla_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_slas', to='sla.sladefinition')),
            ],
            options={
                'db_table': 'task_slas',
                'ordering': ['-created_at'],
            },
        ),
    ]
