# Generated by Django 5.0.6 on 2026-05-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sla', '0004_seed_sla_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksla',
            name='business_elapsed_time',
            field=models.DurationField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='tasksla',
            name='total_pause_duration',
            field=models.DurationField(default='00:00:00'),
        ),
    ]
