# Generated by Django 6.0.4 on 2026-05-10 06:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sla', '0005_alter_tasksla_business_elapsed_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksla',
            name='incident',
        ),
        migrations.AddField(
            model_name='tasksla',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasksla',
            name='object_id',
            field=models.UUIDField(default='00000000-0000-0000-0000-000000000000'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sladefinition',
            name='applies_to',
            field=models.CharField(choices=[('INCIDENT', 'Incident'), ('CHANGE', 'Change'), ('PROBLEM', 'Problem')], default='INCIDENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='tasksla',
            name='business_elapsed_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='tasksla',
            name='total_pause_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddIndex(
            model_name='tasksla',
            index=models.Index(fields=['content_type', 'object_id'], name='task_slas_content_17b49f_idx'),
        ),
    ]
