# Generated by Django 6.0.4 on 2026-05-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sla', '0006_remove_tasksla_incident_tasksla_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksla',
            name='notified_thresholds',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
