# Generated by Django 5.0.6 on 2026-05-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='type',
            field=models.CharField(choices=[('PROMETHEUS', 'Prometheus'), ('GRAFANA', 'Grafana'), ('LOKI', 'Loki'), ('KUBERNETES_CLUSTER', 'Kubernetes Cluster'), ('STACKSTORM', 'StackStorm'), ('DATADOG', 'Datadog'), ('NEW_RELIC', 'New Relic'), ('ELASTICSEARCH', 'Elasticsearch'), ('PAGERDUTY', 'PagerDuty'), ('SERVICENOW', 'ServiceNow'), ('JIRA', 'Jira'), ('OPSGENIE', 'OpsGenie'), ('REDMINE', 'Redmine'), ('SLACK', 'Slack'), ('TEAMS', 'Microsoft Teams'), ('APPRISE', 'Apprise'), ('TWILIO', 'Twilio'), ('MSG91', 'MSG91'), ('WEBHOOK', 'Generic Webhook'), ('EMAIL', 'Email Inbound'), ('N8N', 'n8n'), ('ANSIBLE', 'Ansible'), ('TERRAFORM', 'Terraform'), ('VAULT', 'HashiCorp Vault'), ('AWS', 'AWS CloudWatch'), ('AZURE', 'Azure Monitor')], max_length=20),
        ),
    ]
