# Generated by Django 6.0.4 on 2026-05-08 18:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('trigger', models.CharField(choices=[('ON_CREATE', 'On Create'), ('ON_UPDATE', 'On Update'), ('ON_DELETE', 'On Delete'), ('ON_SLA_BREACH', 'On SLA Breach'), ('ON_TIMER', 'On Timer')], max_length=20)),
                ('target_model', models.CharField(max_length=100)),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('actions', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='organizations.organization')),
            ],
            options={
                'db_table': 'automation_rules',
                'ordering': ['priority', 'name'],
            },
        ),
    ]
