# Generated by Django 5.0.6 on 2026-04-22 08:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeCI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('impact_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'change_cis',
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('NORMAL', 'Normal'), ('STANDARD', 'Standard'), ('EMERGENCY', 'Emergency')], default='NORMAL', max_length=20)),
                ('state', models.CharField(choices=[('NEW', 'New'), ('ASSESSMENT', 'Assessment'), ('APPROVAL', 'Approval'), ('SCHEDULED', 'Scheduled'), ('IMPLEMENTING', 'Implementing'), ('REVIEW', 'Review'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='NEW', max_length=20)),
                ('risk_level', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('implementation_plan', models.TextField(blank=True, null=True)),
                ('rollback_plan', models.TextField(blank=True, null=True)),
                ('test_plan', models.TextField(blank=True, null=True)),
                ('communication_plan', models.TextField(blank=True, null=True)),
                ('planned_start_date', models.DateTimeField(blank=True, null=True)),
                ('planned_end_date', models.DateTimeField(blank=True, null=True)),
                ('actual_start_date', models.DateTimeField(blank=True, null=True)),
                ('actual_end_date', models.DateTimeField(blank=True, null=True)),
                ('affected_services', models.TextField(blank=True, null=True)),
                ('downtime', models.IntegerField(blank=True, null=True)),
                ('user_impact', models.TextField(blank=True, null=True)),
                ('git_repo_url', models.URLField(blank=True, null=True)),
                ('git_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('git_commit_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('pull_request_url', models.URLField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('closure_code', models.CharField(blank=True, choices=[('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'changes',
                'ordering': ['-created_at'],
            },
        ),
    ]
