# Generated by Django 5.0.6 on 2026-04-22 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        ('changes', '0001_initial'),
        ('organizations', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='assignment_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_changes', to='teams.team'),
        ),
        migrations.AddField(
            model_name='change',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='change',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='approval',
            name='change',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='changes.change'),
        ),
        migrations.AddField(
            model_name='changeci',
            name='change',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_cis', to='changes.change'),
        ),
        migrations.AddField(
            model_name='changeci',
            name='config_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_by_changes', to='assets.configurationitem'),
        ),
        migrations.AddIndex(
            model_name='change',
            index=models.Index(fields=['state', 'type'], name='changes_state_da2303_idx'),
        ),
        migrations.AddIndex(
            model_name='change',
            index=models.Index(fields=['planned_start_date'], name='changes_planned_420539_idx'),
        ),
    ]
