# Generated by Django 6.0.4 on 2026-05-10 06:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_configurationitem_firewall_type_and_more'),
        ('changes', '0002_initial'),
        ('organizations', '0002_organization_last_change_number_and_more'),
        ('teams', '0002_escalationpolicy_escalationstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('MAINTENANCE', 'Maintenance Window'), ('BLACKOUT', 'Blackout Period')], default='MAINTENANCE', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_cis', models.ManyToManyField(blank=True, related_name='maintenance_windows', to='assets.configurationitem')),
                ('affected_groups', models.ManyToManyField(blank=True, related_name='maintenance_windows', to='teams.team')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_windows', to='organizations.organization')),
            ],
            options={
                'db_table': 'maintenance_windows',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_data', models.JSONField(default=dict)),
                ('calculated_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment', to='changes.change')),
            ],
            options={
                'db_table': 'change_risk_assessments',
            },
        ),
    ]
