# Generated by Django 5.0.6 on 2026-04-22 08:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('changes', '0002_initial'),
        ('organizations', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('state', models.CharField(choices=[('NEW', 'New'), ('INVESTIGATION', 'Investigation'), ('RCA_IN_PROGRESS', 'RCA In Progress'), ('KNOWN_ERROR', 'Known Error'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='NEW', max_length=20)),
                ('priority', models.CharField(choices=[('P1', 'P1 - Critical'), ('P2', 'P2 - High'), ('P3', 'P3 - Medium'), ('P4', 'P4 - Low')], db_index=True, default='P3', max_length=2)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('root_cause', models.TextField(blank=True, null=True)),
                ('root_cause_analysis', models.JSONField(blank=True, null=True)),
                ('workaround', models.TextField(blank=True, null=True)),
                ('workaround_effective', models.BooleanField(default=False)),
                ('permanent_fix', models.TextField(blank=True, null=True)),
                ('fix_implemented', models.BooleanField(default=False)),
                ('is_known_error', models.BooleanField(default=False)),
                ('known_error_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_problems', to=settings.AUTH_USER_MODEL)),
                ('assignment_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_problems', to='teams.team')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_problems', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='organizations.organization')),
                ('related_change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_problems', to='changes.change')),
            ],
            options={
                'db_table': 'problems',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['state', 'priority'], name='problems_state_aa4e72_idx')],
            },
        ),
    ]
