# Generated by Django 6.0.4 on 2026-05-10 06:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_last_change_number_and_more'),
        ('problems', '0001_initial'),
        ('teams', '0002_escalationpolicy_escalationstep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('state', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=20)),
                ('priority', models.CharField(choices=[('P1', 'P1 - Critical'), ('P2', 'P2 - High'), ('P3', 'P3 - Medium'), ('P4', 'P4 - Low')], default='P3', max_length=2)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_problem_tasks', to=settings.AUTH_USER_MODEL)),
                ('assignment_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_problem_tasks', to='teams.team')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_tasks', to='organizations.organization')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='problems.problem')),
            ],
            options={
                'db_table': 'problem_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
