# Generated by Django 5.0.6 on 2026-04-22 08:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(choices=[('SERVER', 'Server'), ('KUBERNETES_CLUSTER', 'Kubernetes Cluster'), ('DATABASE', 'Database'), ('APPLICATION', 'Application'), ('NETWORK', 'Network'), ('STORAGE', 'Storage'), ('CONTAINER', 'Container'), ('VM', 'Virtual Machine'), ('LOAD_BALANCER', 'Load Balancer')], db_index=True, default='SERVER', max_length=30)),
                ('status', models.CharField(choices=[('LIVE', 'Live'), ('MAINTENANCE', 'Maintenance'), ('DECOMMISSIONED', 'Decommissioned'), ('PLANNED', 'Planned')], db_index=True, default='LIVE', max_length=20)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_tag', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('rack_position', models.CharField(blank=True, max_length=100, null=True)),
                ('data_center', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=255, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('fqdn', models.CharField(blank=True, max_length=255, null=True)),
                ('cpu', models.CharField(blank=True, max_length=255, null=True)),
                ('memory', models.CharField(blank=True, max_length=255, null=True)),
                ('storage', models.CharField(blank=True, max_length=255, null=True)),
                ('os', models.CharField(blank=True, max_length=255, null=True)),
                ('os_version', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('end_of_life', models.DateField(blank=True, null=True)),
                ('end_of_support', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_center', models.CharField(blank=True, max_length=100, null=True)),
                ('monitoring_enabled', models.BooleanField(default=True)),
                ('prometheus_job', models.CharField(blank=True, max_length=255, null=True)),
                ('grafana_dashboard', models.CharField(blank=True, max_length=255, null=True)),
                ('loki_labels', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='organizations.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'configuration_items',
                'ordering': ['name'],
            },
        ),
    ]
