# Generated by Django 5.0.6 on 2026-04-22 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationitem',
            name='support_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supported_assets', to='teams.team'),
        ),
        migrations.AddIndex(
            model_name='configurationitem',
            index=models.Index(fields=['type', 'status'], name='configurati_type_e355e0_idx'),
        ),
        migrations.AddIndex(
            model_name='configurationitem',
            index=models.Index(fields=['hostname'], name='configurati_hostnam_68e944_idx'),
        ),
        migrations.AddIndex(
            model_name='configurationitem',
            index=models.Index(fields=['ip_address'], name='configurati_ip_addr_7c173e_idx'),
        ),
    ]
