# Generated by Django 5.0.6 on 2026-04-23 05:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
        ('organizations', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationitem',
            name='environment',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configurationitem',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configurationitem',
            name='health_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configurationitem',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configurationitem',
            name='management_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configurationitem',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='configurationitem',
            name='service_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='configurationitem',
            name='status',
            field=models.CharField(choices=[('LIVE', 'Live'), ('MAINTENANCE', 'Maintenance'), ('DECOMMISSIONED', 'Decommissioned'), ('PLANNED', 'Planned'), ('IN_STOCK', 'In Stock'), ('RESERVED', 'Reserved'), ('DISPOSED', 'Disposed')], db_index=True, default='LIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='configurationitem',
            name='type',
            field=models.CharField(choices=[('SERVER', 'Server'), ('KUBERNETES_CLUSTER', 'Kubernetes Cluster'), ('DATABASE', 'Database'), ('APPLICATION', 'Application'), ('NETWORK', 'Network'), ('NETWORK_DEVICE', 'Network Device'), ('SWITCH', 'Switch'), ('ROUTER', 'Router'), ('FIREWALL', 'Firewall'), ('STORAGE', 'Storage'), ('CONTAINER', 'Container'), ('VM', 'Virtual Machine'), ('LOAD_BALANCER', 'Load Balancer'), ('SOFTWARE', 'Software'), ('END_USER_DEVICE', 'End User Device'), ('MONITOR', 'Monitor'), ('PERIPHERAL', 'Peripheral'), ('SIMCARD', 'SIM Card'), ('PHONE', 'Phone'), ('PRINTER', 'Printer'), ('RACK_UNIT', 'Rack Unit'), ('PDU', 'Power Distribution Unit'), ('ENCLOSURE', 'Enclosure'), ('CABLE', 'Cable'), ('UPS', 'UPS')], db_index=True, default='SERVER', max_length=30),
        ),
        migrations.CreateModel(
            name='AssetCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('SERVER_TYPE', 'Server Type'), ('SERVER_OS', 'Server OS'), ('SERVER_SOFTWARE', 'Server Software'), ('SERVER_NIC', 'Server NIC'), ('SWITCH_LAYER', 'Switch Layer'), ('SWITCH_MODEL', 'Switch Model'), ('FIREWALL_TYPE', 'Firewall Type'), ('FIREWALL_MODEL', 'Firewall Model'), ('ROUTER_TYPE', 'Router Type'), ('ROUTER_MODEL', 'Router Model'), ('SOFTWARE', 'Software'), ('APPLICATION', 'Application')], db_index=True, max_length=40)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_catalog_items', to='organizations.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='assets.assetcatalog')),
            ],
            options={
                'db_table': 'asset_catalog',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssetDiscoveryResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_range_start', models.GenericIPAddressField(blank=True, null=True)),
                ('scan_range_end', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_type', models.CharField(choices=[('SERVER', 'Server'), ('KUBERNETES_CLUSTER', 'Kubernetes Cluster'), ('DATABASE', 'Database'), ('APPLICATION', 'Application'), ('NETWORK', 'Network'), ('NETWORK_DEVICE', 'Network Device'), ('SWITCH', 'Switch'), ('ROUTER', 'Router'), ('FIREWALL', 'Firewall'), ('STORAGE', 'Storage'), ('CONTAINER', 'Container'), ('VM', 'Virtual Machine'), ('LOAD_BALANCER', 'Load Balancer'), ('SOFTWARE', 'Software'), ('END_USER_DEVICE', 'End User Device'), ('MONITOR', 'Monitor'), ('PERIPHERAL', 'Peripheral'), ('SIMCARD', 'SIM Card'), ('PHONE', 'Phone'), ('PRINTER', 'Printer'), ('RACK_UNIT', 'Rack Unit'), ('PDU', 'Power Distribution Unit'), ('ENCLOSURE', 'Enclosure'), ('CABLE', 'Cable'), ('UPS', 'UPS')], default='SERVER', max_length=30)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACCEPTED', 'Accepted'), ('IGNORED', 'Ignored')], db_index=True, default='NEW', max_length=20)),
                ('discovered_data', models.JSONField(blank=True, default=dict)),
                ('discovered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_ci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_discovery_results', to='assets.configurationitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_discovery_results', to='organizations.organization')),
            ],
            options={
                'db_table': 'asset_discovery_results',
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetManagementEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('protocol', models.CharField(choices=[('IDRAC', 'iDRAC'), ('ILO', 'iLO'), ('SNMP', 'SNMP'), ('NODE_EXPORTER', 'Node Exporter'), ('WINDOWS_EXPORTER', 'Windows Exporter'), ('NGINX_EXPORTER', 'Nginx Exporter'), ('REDFISH', 'Redfish'), ('SSH', 'SSH'), ('WINRM', 'WinRM'), ('API', 'API')], db_index=True, max_length=40)),
                ('management_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ilo_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('secret_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('threshold', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_endpoints', to='assets.configurationitem')),
            ],
            options={
                'db_table': 'asset_management_endpoints',
                'ordering': ['protocol', 'management_ip'],
            },
        ),
        migrations.CreateModel(
            name='AssetPortConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_modal', models.CharField(blank=True, max_length=255, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('source_port', models.CharField(max_length=100)),
                ('source_name', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_modal', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('destination_port', models.CharField(max_length=100)),
                ('destination_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PLANNED', 'Planned'), ('DOWN', 'Down'), ('RETIRED', 'Retired')], db_index=True, default='ACTIVE', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_port_connections', to='organizations.organization')),
                ('source_ci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_port_connections', to='assets.configurationitem')),
                ('target_ci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_port_connections', to='assets.configurationitem')),
            ],
            options={
                'db_table': 'asset_port_connections',
                'ordering': ['source_name', 'source_port'],
            },
        ),
        migrations.CreateModel(
            name='AssetRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('DEPENDS_ON', 'Depends On'), ('CONNECTS_TO', 'Connects To'), ('HOSTS', 'Hosts'), ('RUNS_ON', 'Runs On'), ('MANAGES', 'Manages'), ('MONITORS', 'Monitors'), ('RELATED_TO', 'Related To')], db_index=True, default='RELATED_TO', max_length=30)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('source_port', models.CharField(blank=True, max_length=100, null=True)),
                ('target_port', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_asset_relationships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_relationships', to='organizations.organization')),
                ('source_ci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='assets.configurationitem')),
                ('target_ci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='assets.configurationitem')),
            ],
            options={
                'db_table': 'asset_relationships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=140)),
                ('environment', models.CharField(db_index=True, default='Production', max_length=100)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=120, null=True)),
                ('state', models.CharField(blank=True, max_length=120, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('entity_host', models.CharField(blank=True, max_length=255, null=True)),
                ('entity_port', models.PositiveIntegerField(blank=True, null=True)),
                ('entity_secure', models.BooleanField(default=False)),
                ('websocket_host', models.CharField(blank=True, max_length=255, null=True)),
                ('websocket_port', models.PositiveIntegerField(blank=True, null=True)),
                ('websocket_secure', models.BooleanField(default=False)),
                ('redis_url', models.CharField(blank=True, max_length=500, null=True)),
                ('prometheus_url', models.URLField(blank=True, max_length=500, null=True)),
                ('grafana_url', models.URLField(blank=True, max_length=500, null=True)),
                ('redmine_url', models.URLField(blank=True, max_length=500, null=True)),
                ('incident_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEGRADED', 'Degraded'), ('OFFLINE', 'Offline'), ('RETIRED', 'Retired')], db_index=True, default='ACTIVE', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_sites', to='organizations.organization')),
            ],
            options={
                'db_table': 'asset_sites',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetOnboardingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('select_host', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('sub_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('server_type', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('service_name', models.CharField(blank=True, max_length=255, null=True)),
                ('path_host', models.CharField(blank=True, max_length=255, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('physical_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('main_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATED', 'Validated'), ('ONBOARDED', 'Onboarded'), ('FAILED', 'Failed')], db_index=True, default='DRAFT', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_records', to='assets.configurationitem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_onboarding_records', to=settings.AUTH_USER_MODEL)),
                ('discovery_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_records', to='assets.assetdiscoveryresult')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_onboarding_records', to='organizations.organization')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_records', to='assets.assetsite')),
            ],
            options={
                'db_table': 'asset_onboarding_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assetdiscoveryresult',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_results', to='assets.assetsite'),
        ),
        migrations.AddField(
            model_name='configurationitem',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuration_items', to='assets.assetsite'),
        ),
        migrations.AddIndex(
            model_name='configurationitem',
            index=models.Index(fields=['organization', 'type'], name='configurati_organiz_f2e6c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetcatalog',
            unique_together={('organization', 'category', 'name')},
        ),
        migrations.AddIndex(
            model_name='assetportconnection',
            index=models.Index(fields=['organization', 'status'], name='asset_port__organiz_a46911_idx'),
        ),
        migrations.AddIndex(
            model_name='assetportconnection',
            index=models.Index(fields=['source_ip'], name='asset_port__source__e5f316_idx'),
        ),
        migrations.AddIndex(
            model_name='assetportconnection',
            index=models.Index(fields=['destination_ip'], name='asset_port__destina_cc5faa_idx'),
        ),
        migrations.AddIndex(
            model_name='assetrelationship',
            index=models.Index(fields=['organization', 'relationship_type'], name='asset_relat_organiz_17fddc_idx'),
        ),
        migrations.AddIndex(
            model_name='assetrelationship',
            index=models.Index(fields=['source_ci', 'target_ci'], name='asset_relat_source__cd4396_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetsite',
            unique_together={('organization', 'slug')},
        ),
        migrations.AddIndex(
            model_name='assetdiscoveryresult',
            index=models.Index(fields=['organization', 'status'], name='asset_disco_organiz_39e0d0_idx'),
        ),
        migrations.AddIndex(
            model_name='assetdiscoveryresult',
            index=models.Index(fields=['organization', 'ip_address'], name='asset_disco_organiz_89a49b_idx'),
        ),
    ]
