# Generated by Django 5.0.6 on 2026-04-24 01:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_configurationitem_environment_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configurationitem',
            options={'default_manager_name': 'objects', 'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='ConfigurationItemHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_source', models.CharField(choices=[('user', 'User'), ('worker', 'Worker'), ('import', 'Import'), ('system', 'System')], default='system', max_length=20)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuration_item_history_entries', to=settings.AUTH_USER_MODEL)),
                ('configuration_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='assets.configurationitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_item_history', to='organizations.organization')),
            ],
            options={
                'db_table': 'configuration_item_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
