# Generated by Django 5.0.6 on 2026-05-04 08:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_configurationitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationitem',
            name='firewall_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='configurationitem',
            name='metrics_management_interfaces',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configurationitem',
            name='network_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='configurationitem',
            name='physical_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configurationitem',
            name='router_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='configurationitem',
            name='switch_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='configurationitem',
            name='template',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AssetMetricsManagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ilo_enabled', models.BooleanField(default=False)),
                ('ilo_username', models.CharField(blank=True, max_length=255, null=True)),
                ('ilo_password', models.CharField(blank=True, max_length=255, null=True)),
                ('ilo_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('idrac_enabled', models.BooleanField(default=False)),
                ('idrac_port', models.PositiveIntegerField(blank=True, null=True)),
                ('node_exporter_enabled', models.BooleanField(default=False)),
                ('node_exporter_port', models.PositiveIntegerField(blank=True, null=True)),
                ('windows_exporter_enabled', models.BooleanField(default=False)),
                ('windows_exporter_port', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_management', to='assets.configurationitem')),
            ],
            options={
                'verbose_name': 'Asset Metrics Management',
                'verbose_name_plural': 'Asset Metrics Management',
                'db_table': 'asset_metrics_management',
            },
        ),
        migrations.CreateModel(
            name='AssetSNMPConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snmp_enabled', models.BooleanField(default=False)),
                ('snmp_version', models.CharField(blank=True, max_length=10, null=True)),
                ('snmp_community_string', models.CharField(blank=True, max_length=255, null=True)),
                ('snmp_username', models.CharField(blank=True, max_length=255, null=True)),
                ('snmp_security_level', models.CharField(blank=True, max_length=50, null=True)),
                ('snmp_auth_method', models.CharField(blank=True, max_length=50, null=True)),
                ('snmp_auth_password', models.CharField(blank=True, max_length=255, null=True)),
                ('snmp_privacy_method', models.CharField(blank=True, max_length=50, null=True)),
                ('snmp_privacy_password', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snmp_configurations', to='assets.configurationitem')),
            ],
            options={
                'verbose_name': 'Asset SNMP Configuration',
                'verbose_name_plural': 'Asset SNMP Configurations',
                'db_table': 'asset_snmp_configurations',
            },
        ),
    ]
