from django.urls import path
from .views import (
    AssetCatalogListCreateView,
    AssetDiscoveryResultListView,
    AssetDiscoveryScanView,
    AssetAllocationReturnView,
    AssetAllocationsView,
    AssetConnectionsView,
    AssetDependencyMapView,
    AssetDisposalView,
    AssetFinancialsView,
    AssetManagementEndpointListCreateView,
    AssetMovementsView,
    AssetOnboardView,
    AssetOnboardingListView,
    AssetIPAddressesView,
    AssetPortConnectionExportView,
    AssetPortConnectionImportView,
    AssetPortConnectionListCreateView,
    AssetLiveMetricsView,
    AssetLiveStatusSyncView,
    AssetMetricsHistoryView,
    AssetPrometheusConfigView,
    AssetRelationshipCompatView,
    AssetRelationshipDeleteCompatView,
    AssetRelationshipListCreateView,
    AssetSiteDetailView,
    AssetSiteListCreateView,
    AssetTopologyView,
    AssetTypesView,
    AssetVendorDetailView,
    AssetVendorsView,
    ConfigurationItemDetailView,
    ConfigurationItemListCreateView,
    ConfigurationItemStatsView,
)

urlpatterns = [
    path("stats/", ConfigurationItemStatsView.as_view(), name="ci-stats"),
    path("types/", AssetTypesView.as_view(), name="asset-types"),
    path("sites/", AssetSiteListCreateView.as_view(), name="asset-sites"),
    path("sites/<uuid:pk>/", AssetSiteDetailView.as_view(), name="asset-site-detail"),
    path("catalog/", AssetCatalogListCreateView.as_view(), name="asset-catalog"),
    path("topology/", AssetTopologyView.as_view(), name="asset-topology"),
    path("live-status/sync/", AssetLiveStatusSyncView.as_view(), name="asset-live-status-sync"),
    path("prometheus/config/", AssetPrometheusConfigView.as_view(), name="asset-prometheus-config"),
    path("vendors", AssetVendorsView.as_view(), name="asset-vendors"),
    path("vendors/<slug:vendor_id>", AssetVendorDetailView.as_view(), name="asset-vendor-detail"),
    path("port-connections/", AssetPortConnectionListCreateView.as_view(), name="asset-port-connections"),
    path("port-connections/import/", AssetPortConnectionImportView.as_view(), name="asset-port-connections-import"),
    path("port-connections/export/", AssetPortConnectionExportView.as_view(), name="asset-port-connections-export"),
    path("autodiscover/scan/", AssetDiscoveryScanView.as_view(), name="asset-discovery-scan"),
    path("autodiscover/results/", AssetDiscoveryResultListView.as_view(), name="asset-discovery-results"),
    path("onboarding/", AssetOnboardingListView.as_view(), name="asset-onboarding-list"),
    path("onboard/", AssetOnboardView.as_view(), name="asset-onboard"),
    path("", ConfigurationItemListCreateView.as_view(), name="ci-list-create"),
    path("<uuid:pk>/management-endpoints/", AssetManagementEndpointListCreateView.as_view(), name="asset-management-endpoints"),
    path("<uuid:pk>/relationships", AssetRelationshipCompatView.as_view(), name="asset-relationships-compat"),
    path("<uuid:pk>/relationships/<uuid:relationship_id>", AssetRelationshipDeleteCompatView.as_view(), name="asset-relationships-delete-compat"),
    path("<uuid:pk>/relationships/", AssetRelationshipListCreateView.as_view(), name="asset-relationships"),
    path("<uuid:pk>/dependency-map", AssetDependencyMapView.as_view(), name="asset-dependency-map"),
    path("<uuid:pk>/financials", AssetFinancialsView.as_view(), name="asset-financials"),
    path("<uuid:pk>/allocations", AssetAllocationsView.as_view(), name="asset-allocations"),
    path("<uuid:pk>/allocations/<uuid:allocation_id>/return", AssetAllocationReturnView.as_view(), name="asset-allocation-return"),
    path("<uuid:pk>/disposal", AssetDisposalView.as_view(), name="asset-disposal"),
    path("<uuid:pk>/movements", AssetMovementsView.as_view(), name="asset-movements"),
    path("<uuid:pk>/connections", AssetConnectionsView.as_view(), name="asset-connections"),
    path("<uuid:pk>/ip-addresses", AssetIPAddressesView.as_view(), name="asset-ip-addresses"),
    path("<uuid:pk>/live-metrics/", AssetLiveMetricsView.as_view(), name="asset-live-metrics"),
    path("<uuid:pk>/metrics-history/", AssetMetricsHistoryView.as_view(), name="asset-metrics-history"),
    path("<uuid:pk>/", ConfigurationItemDetailView.as_view(), name="ci-detail"),
]
