# Generated by Django 6.0.4 on 2026-05-10 05:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_last_change_number_and_more'),
        ('teams', '0002_escalationpolicy_escalationstep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('conditions', models.JSONField(help_text='JSON conditions for rule matching')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_rules', to='organizations.organization')),
                ('target_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_rules', to='teams.team')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assignment_rules',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryGroupMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_mappings', to='organizations.organization')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_mappings', to='teams.team')),
            ],
            options={
                'db_table': 'category_group_mappings',
                'unique_together': {('organization', 'category', 'subcategory')},
            },
        ),
        migrations.CreateModel(
            name='RoundRobinCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_assigned_at', models.DateTimeField(auto_now=True)),
                ('last_assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_robin_counters', to='organizations.organization')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_robin_counter', to='teams.team')),
            ],
            options={
                'db_table': 'round_robin_counters',
                'unique_together': {('organization', 'team')},
            },
        ),
        migrations.CreateModel(
            name='SkillRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('skill_name', models.CharField(max_length=100)),
                ('min_proficiency', models.PositiveSmallIntegerField(default=1)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='organizations.organization')),
            ],
            options={
                'db_table': 'skill_requirements',
                'unique_together': {('organization', 'category', 'subcategory', 'skill_name')},
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=100)),
                ('proficiency', models.PositiveSmallIntegerField(default=1, help_text='Proficiency level 1-5')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_skills',
                'unique_together': {('user', 'skill_name')},
            },
        ),
    ]
