# Generated by Django 6.0.4 on 2026-05-08 18:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_permission_remove_user_role_and_more'),
        ('organizations', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_policies', to='organizations.organization')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_policies', to='teams.team')),
            ],
            options={
                'db_table': 'escalation_policies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EscalationStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.PositiveIntegerField()),
                ('wait_time_minutes', models.PositiveIntegerField(help_text='Minutes to wait before escalating to the next level')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notify_roles', models.ManyToManyField(blank=True, related_name='escalation_steps', to='accounts.role')),
                ('notify_users', models.ManyToManyField(blank=True, related_name='escalation_steps', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='teams.escalationpolicy')),
            ],
            options={
                'db_table': 'escalation_steps',
                'ordering': ['step_number'],
                'unique_together': {('policy', 'step_number')},
            },
        ),
    ]
