# Generated by Django 5.0.6 on 2026-04-24 01:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnmatchedAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('alert_name', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'unmatched_alerts',
                'ordering': ['-received_at'],
            },
        ),
    ]
