# Generated by Django 5.0.6 on 2026-04-24 10:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0002_initial'),
        ('incidents', '0002_unmatchedalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_incidents', to='changes.change')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_changes', to='incidents.incident')),
            ],
            options={
                'db_table': 'incident_changes',
            },
        ),
        migrations.AddConstraint(
            model_name='incidentchange',
            constraint=models.UniqueConstraint(fields=('incident', 'change'), name='uniq_incident_change_link'),
        ),
    ]
