# Generated by Django 5.0.6 on 2026-05-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_activity_audit_sla_notify_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='incident',
            new_name='incidents_organiz_b7b8b7_idx',
            old_name='incidents_org_state_created_idx',
        ),
        migrations.RenameIndex(
            model_name='incident',
            new_name='incidents_organiz_4be80c_idx',
            old_name='incidents_org_pri_created_idx',
        ),
    ]
