# Generated by Django 5.0.6 on 2026-05-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_rename_incidents_org_state_created_idx_incidents_organiz_b7b8b7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='auto_created',
            field=models.BooleanField(db_index=True, default=False, help_text='Incident was created automatically from alert'),
        ),
        migrations.AddField(
            model_name='incident',
            name='auto_creation_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata about automatic creation process'),
        ),
        migrations.AddField(
            model_name='incident',
            name='threshold_rule_id',
            field=models.UUIDField(blank=True, help_text='Threshold rule that triggered this incident', null=True),
        ),
    ]
