# Generated by Django 5.0.6 on 2026-05-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0008_add_auto_creation_audit_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='auto_created',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='auto_creation_metadata',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='threshold_rule_id',
        ),
    ]
