# Generated by Django 6.0.4 on 2026-05-10 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0009_remove_incident_auto_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='is_major_incident',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='major_incident_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='major_incident_state',
            field=models.CharField(blank=True, choices=[('PROPOSED', 'Proposed'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELED', 'Canceled')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_incidents', to='incidents.incident'),
        ),
    ]
