# Generated by Django 6.0.4 on 2026-05-15 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_configurationitem_firewall_type_and_more'),
        ('incidents', '0011_incident_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='assets.assetsite'),
        ),
    ]
