# Generated by Codex on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0012_add_site_and_location_to_incident"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["organization", "source_alert_id", "state"],
                name="incidents_organiz_b99a3c_idx",
            ),
        ),
    ]
