# Generated by Django 6.0.4 on 2026-05-08 18:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subject_template', models.CharField(blank=True, max_length=255)),
                ('body_template', models.TextField()),
                ('type', models.CharField(choices=[('INCIDENT', 'Incident'), ('CHANGE', 'Change'), ('PROBLEM', 'Problem'), ('ALERT', 'Alert'), ('SLA', 'SLA'), ('SYSTEM', 'System')], max_length=20)),
                ('channel', models.CharField(choices=[('WEB', 'Web'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('SLACK', 'Slack'), ('VOICE', 'Voice')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='organizations.organization')),
            ],
            options={
                'db_table': 'notification_templates',
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
